version: "3"
services:
  producer-db:
    image: debezium/postgres:13
    container_name: producer-db
    hostname: producer-db
    environment:
      POSTGRES_PASSWORD: root_password  # please change it
      POSTGRES_DB: producer
    ports:
      - 5433:5432

  comsumer-db:
    image: debezium/postgres:13
    container_name: comsumer-db
    hostname: comsumer-db
    environment:
      POSTGRES_PASSWORD: root_password  # please change it
      POSTGRES_DB: comsumer
    ports:
      - 5434:5432

  zookeeper:
    image: debezium/zookeeper:2.0
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      JMXPORT: 9010
      JMXHOST: zookeeper

  kafka1:
    image: debezium/kafka:2.0
    container_name: kafka1
    restart: always
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      BROKER_ID: 1
      ADVERTISED_HOST_NAME: kafka1
      JMXPORT: 9011
      JMXHOST: kafka1
    depends_on:
      - zookeeper

  kafka2:
    image: debezium/kafka:2.0
    container_name: kafka2
    restart: always
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      BROKER_ID: 2
      ADVERTISED_HOST_NAME: kafka2
      JMXPORT: 9011
      JMXHOST: kafka2
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:29092,kafka2:29093"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9011
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083

  connect:
    image: debezium/connect:2.0
    container_name: connect
    restart: always
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: "kafka1:29092,kafka2:29093"
      JMXPORT: 9012
      JMXHOST: connect
    depends_on:
      - kafka1
      - kafka2
